Fix refresh device info before each operation
NordicSemiconductor/pc-nrfconnect-programmer pull request #471
Opened 2024-08-27 11:40 UTC by kylebonnici

This PR updates the device info before any major acton as with jlink (external for example) the connected SOC might change and we do not want to manipulate a hex file using the wrong SOC when programming

2024-08-27 11:41 UTC, KievDevel commented on Changelog.md
> +## 4.4.1 - 2024-08-23
```suggestion
## 4.4.1 - unreleased
```

2024-09-02 11:16 UTC, greg-fer requested changes

2024-09-02 11:16 UTC, greg-fer commented on Changelog.md
> +    between operation programer will still work as expected
```suggestion
-   The SoC is now detected before each operation to ensure the app works
    even if the SoC changes between operations.
```

2024-09-02 13:18 UTC, KievDevel commented on Changelog.md
> +    between operation programer will still work as expected
Looks good, so commit

2024-09-03 12:32 UTC, merged