Fix: Programmer warns of dect firmware file name
NordicSemiconductor/pc-nrfconnect-programmer pull request #476
Opened 2024-10-07 22:50 UTC by KievDevel

2024-10-08 08:14 UTC, greg-fer requested changes

2024-10-08 08:14 UTC, greg-fer commented on Changelog.md
> +-   Now DECT modem firmware is correctly detected for 91x family.
```suggestion
-   The DECT modem firmware is now correctly detected for nRF91x1 devices.
```
91x is not allowed, and 91x is not a family: https://nordicsemi.atlassian.net/wiki/spaces/MAR/pages/132940950/Product+names

2024-10-18 10:45 UTC, kylebonnici approved these changes

2024-10-18 11:27 UTC, greg-fer approved these changes

2024-10-18 13:00 UTC, merged