Fix/large fw nrf54l15
NordicSemiconductor/pc-nrfconnect-programmer pull request #488
Opened 2024-12-12 15:38 UTC by kylebonnici

2024-12-13 11:48 UTC, greg-fer requested changes

2024-12-13 11:48 UTC, greg-fer commented on Changelog.md
> +-   Disable unsupported firmware read for nRF54L Family.
```suggestion
### Changed

-   Disabled unsupported firmware read for nRF54L Series.

### Fixed

-   Issue with programming firmware on nRF54L15 when it is larger than 1 MB.
```

2024-12-13 11:50 UTC, greg-fer commented
What should we do about the table in https://docs.nordicsemi.com/bundle/nrf-connect-programmer/page/index.html ? Slava said there are issues with programming nRF54L in another task, and now we're adding entries for nRF54L as if it is supported all right.
We need to update that table.

2024-12-15 15:00 UTC, KievDevel commented on Changelog.md
> +## 4.4.3 - UNRELESED
```suggestion
## 4.5.0 - UNRELESED
```

2024-12-15 15:00 UTC, KievDevel commented on package.json
> +    "version": "4.4.3",
```suggestion
    "version": "4.5.0",
```

2024-12-16 15:08 UTC, KievDevel commented on Changelog.md
> +## 4.5.0 - UNRELEASED
```suggestion
## 4.5.0 - 2024-12-17
```

2024-12-16 15:36 UTC, merged